import wizards from "../Tabs/img/image 1.png"
import life from "../Tabs/img/image 2.png"

const fakeBackend=[
    {
        id:1,
        title:"Все разделы",
        isDone:false,
        books:[
            {
                id:1,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:2,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:3,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:4,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:5,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                img:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:6,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:7,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:8,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:9,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:7,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:8,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:9,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },

        ],

    },
    {
        id:2,
        title:"Новое",
        isDone:false,
        books:[
            {
                id:1,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:2,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:3,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:4,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:5,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:6,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:7,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:8,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:7,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:8,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:9,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:9,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },

        ],
    },
    {
        id:3,
        title:"Софт-скилс",
        isDone:false,
        books:[
            {
                id:1,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:2,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:3,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:4,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:5,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:6,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:7,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:8,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:9,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },

        ],
    },
    {
        id:4,
        title:"Книги",
        isDone:false,
        books:[
            {
                id:1,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:2,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:3,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:4,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:5,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:6,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:7,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:8,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:7,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:8,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:9,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:9,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },



        ],
    },
    {
        id:5,
        title:"Окружение",
        isDone:false,
        books:[
            {
                id:1,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:2,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:3,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:4,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:5,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:6,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:7,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:8,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:9,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:7,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:8,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:wizards,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },
            {
                id:9,
                title:"С какой книги начать?",
                text:"Полезные статьи",
                textAll:"все",
                textNew:"Новое",
                textBooks:"Книги",
                images:life,
                author:"Автор: Muslim Bolot",
                data:"Дата: 22.08.22",
            },

        ],
    }


]
export default fakeBackend ;