import {LanguageContext} from "./index"
import {useState} from "react";
import wizards from "../../Pages/Tabs/img/image 1.png";
import life from "../../Pages/Tabs/img/image 2.png";
import line from "../../Pages/Rewiew/img/Line 8.png";


const RootContext = ({children}) => {
    const data = [
        {
            card: {
                title: "Подпишитесь сейчас за 250,00 $ / год",
                desc: "И получи доступ ко всем нашим материалам и начинай развиваться сейчас вместе со всеми",
                sub: "Подписаться",
                know: "Узнать больше",

                titleKG: "Жылына $250.00 үчүн азыр жазылыңыз",
                descKG: "Жана биздин бардык материалдарга мүмкүнчүлүк алыңыз жана азыр бардыгы менен иштеп баштаңыз",
                subKG: "Подписаться",
                knowKG: "Көбүрөөк билүү үчүн",
            },
            accord: {
                name: "Появились вопросы?",
                question1: "Сколько всего насчитывается материала всего?",
                question2: "Потеряю ли я оставшесея время если перейду на другой до окончания этого?",
                question3: "Могу ли я отказаться от автопродления подписки?",
                question4: "Откуда мне узнавать про новые статьи и курсы?",
                title: "К сожелению мы уже утратили счет материала спустьа столько лет работы и уже их настолько много что их уже не",

                nameKG: "Суроолор барбы?",
                question1KG: "Жалпыда жеткиликтүү материалдар канча?",
                question2KG: "ББул убакыт бүтө электе башкасына өтсөм, калган убактымды текке кетиремби?",
                question3KG: "Жазылуумду автоматтык түрдө жаңылоодон баш тарта аламбы?",
                question4KG: "Жаңы макалалар жана курстар жөнүндө кантип билсем болот?",
                titleKG: "Тилекке каршы, биз ушунча жыл иштегенден кийин материалдардын эсебин жоготуп алдык жана алар ушунчалык көп болгондуктан, алар азыр жок.../"
            },

        }
    ];
    const reviews = [
        {
            title: "Твой опыт бесценен! Ты бьешь в самое сердце и в этом твой успех, любого бизнесмена! У меня есть шанс научиться на твоих ошибках. Этот опыт бесценен!",
            text: "Смотреть полностью",
            name: "Muslim Bolot",
            lastTitle: "Предпрениматель",
            img: line,

            titleKG: "Сиздин тажрыйба баа жеткис! Сен жүрөгүңдү согуп жатасың жана бул сенин ийгилигиң, каалаган бизнесмен! Мен сенин каталарыңдан сабак алууга мүмкүнчүлүгүм бар. Бул тажрыйба баа жеткис! ",
            textKG: "  Баардыгын коруу",
            nameKG: "Абытаева Савия",
            lastTitleKG: "Ишкер "


        },
        {
            title: "Твой опыт бесценен! Ты бьешь в самое сердце и в этом твой успех, любого бизнесмена! У меня есть шанс научиться на твоих ошибках. Этот опыт бесценен!",
            text: "Смотреть полностью",
            name: "Muslim Bolot",
            lastTitle: "Предпрениматель",
            img: line,

            titleKG: "Сиздин тажрыйба баа жеткис! Сен жүрөгүңдү согуп жатасың жана бул сенин ийгилигиң, каалаган бизнесмен! Мен сенин каталарыңдан сабак алууга мүмкүнчүлүгүм бар. Бул тажрыйба баа жеткис! ",
            textKG: "  Баардыгын коруу",
            nameKG: "Абытаева Савия",
            lastTitleKG: "Ишкер "


        },
        {
            title: "Твой опыт бесценен! Ты бьешь в самое сердце и в этом твой успех, любого бизнесмена! У меня есть шанс научиться на твоих ошибках. Этот опыт бесценен!",
            text: "Смотреть полностью",
            name: "Muslim Bolot",
            lastTitle: "Предпрениматель",
            img: line,

            titleKG: "Сиздин тажрыйба баа жеткис! Сен жүрөгүңдү согуп жатасың жана бул сенин ийгилигиң, каалаган бизнесмен! Мен сенин каталарыңдан сабак алууга мүмкүнчүлүгүм бар. Бул тажрыйба баа жеткис! ",
            textKG: "  Баардыгын коруу",
            nameKG: "Абытаева Савия",
            lastTitleKG: "Ишкер "

        },
    ];
const check = [
    {
        self: "SELF DEVELOPING SCHOOL",
        panding: "Ожидание оплаты",
        result: 'Спасибо за оплату.',
        chek:'Чек был выслан на вашу электронную почту'
    }
]
    const subscribe = [
        {   sub: "Подписаться",
            decor: "Оформление подписки",
            decorKG:"Жазылуу",

            name: {
                title: "ФИО",
                input: "Muslim Bolot Joodarovich",

                titleKG: "Аты-жөнү",
                inputKG: "Muslim Bolot Joodarovich"
            },
            email: {
                title: "Электронная почта",
                input: "Example@gmail.com",

                titleKG: "Электрондук почта",
                inputKG: "Example@gmail.com"
            },
            number: {
                title: "Номер телефона",
                input: "+996 770 55 55 55 ",

                titleKG: "Телефон номери",
                inputKG: "+996 770 55 55 55 "
            },
            password: {
                title: "Промокод",
                input: "If you do have",
                titleKG: "Промокод",
                inputKG: "Эгер сизде бар болсо"
            },
            pay: {
                title: "Оплата",
                visa: "Visa",
                card: "Master Card",
                titleKG: "Төлөм"
            },
            cart: {
                title: "Номер карты",
                term: "Срок",
                time: "CVV",

                titleKG: "Картанын номери",
                termKG: "термин",
                timeKG: "CVV",
            },

            average: {
                title: "Уровень пакета",
                usual: "Обычный",
                usual2: "Ежемесячно",
                usual3: "Ежегодно",
                usual4: "Все новые статьи",
                usual5: "Все мастер классы по саморозвитию",
                usual6: "Цена: 225$",
                usual7: "Выбрано",


                titleKG: "Пакет деңгээли",
                usualKG: "кадимки",
                usual2KG: "Ай сайын",
                usual3KG: "Жыл сайын",
                usual4KG: "Бардык жаңы макалалар",
                usual5KG: "Өзүн-өзү өнүктүрүү боюнча бардык мастер-класстар",
                usual6KG: "Баасы: $225",
                usual7KG: "Тандалган",

                usualCoin: "250$"
            },
            intensive: {
                title2: "Интенсив",
                careful: "Ежемесячно",
                careful1: "Ежегодно",
                careful2: "Все новые статьи",
                careful3: "Все мастер классы по саморозвитию",
                careful4: "Курс по чтению языка тела",
                careful5: "Курс по накоплению средств с выполотой долгов",
                careful6: "Курс по быстрому карьерному росту",
                careful7: "Курс по одолеванию страха потери",
                coin: "Цена: 500$",
                coin2: "750$",
                Choose: "Выбрать",

                title2KG: "Интенсивдүү",
                carefulKG: "Ай сайын",
                careful1KG: "Жыл сайын",
                careful2KG: "Бардык жаңы макалалар",
                careful3KG: "Өзүн-өзү өнүктүрүү боюнча бардык мастер-класстар",
                careful4KG: "Денени окуу курсу",
                careful5KG: "Карыздарды отоо чөптөр менен топтоо боюнча курс",
                careful6KG: "Тез мансап өсүү курсу",
                careful7KG: "Жоготуу коркунучун жеңүү курсу",
                coinKG: "Баасы: $500",
                coin2KG: "750$",
                ChooseKG: "Тандоо",

                dollar: "500$",
            },
            btn: "Оплатить ",
            agree: "Я ознакомился и согласен с Условиями оказания услуг",
            btnKG: "Төлөө",
            agreeKG: "Мен Тейлөө шарттарын окуп чыктым жана макулмун"




        }
    ];
    const accordion = [

        {
            levelKG: "Курстун программасы",
            btn1: "Модуль 1",
            btn2: " 1 неделя",
            main: "main",
            title: "Введение",
            task1: "Урок 1: Введение в курс ",
            task2: "Урок 2: Бизнес онлайн и офлайн",
            task3: " Урок 3: Имидж компании",
            text: " Результат модуля: вы узнаете, как будет проходить обучение, познакомитесь с трекером и другими участниками курса.",

            btn2KG: "1 жума",
            titleKG: "Киришүү ",
            task1KG: "1-сабак: курска киришүү ",
            task2KG: "2-сабак: онлайн жана оффлайн Бизнес",
            task3KG: " 3-сабак: компаниянын имиджи",
            textKG: " Модулдун натыйжасы: тренинг кандай өтөөрүн, трекер жана курстун башка катышуучулары менен таанышууну үйрөнөсүз.",

        },
        {
            btn1: "Модуль 2",
            btn2: " 1 неделя",
            main: "main",
            title: "Введение",
            task1: "Урок 1: Введение в курс ",
            task2: "Урок 2: Бизнес онлайн и офлайн",
            task3: " Урок 3: Имидж компании",
            text: " Результат модуля: вы узнаете, как будет проходить обучение, познакомитесь с трекером и другими участниками курса.",

            btn2KG: "1 жума",
            titleKG: "Киришүү ",
            task1KG: "1-сабак: курска киришүү ",
            task2KG: "2-сабак: онлайн жана оффлайн Бизнес",
            task3KG: " 3-сабак: компаниянын имиджи",
            textKG: " Модулдун натыйжасы: тренинг кандай өтөөрүн, трекер жана курстун башка катышуучулары менен таанышууну үйрөнөсүз.",

        },
        {
            btn1: "Модуль 3",
            btn2: " 1 неделя",
            main: "main",
            title: "Введение",
            task1: "Урок 1: Введение в курс ",
            task2: "Урок 2: Бизнес онлайн и офлайн",
            task3: " Урок 3: Имидж компании",
            text: " Результат модуля: вы узнаете, как будет проходить обучение, познакомитесь с трекером и другими участниками курса.",

            btn2KG: "1 жума",
            titleKG: "Киришүү ",
            task1KG: "1-сабак: курска киришүү ",
            task2KG: "2-сабак: онлайн жана оффлайн Бизнес",
            task3KG: " 3-сабак: компаниянын имиджи",
            textKG: " Модулдун натыйжасы: тренинг кандай өтөөрүн, трекер жана курстун башка катышуучулары менен таанышууну үйрөнөсүз.",

        },
        {
            btn1: "Модуль 4",
            btn2: " 1 неделя",
            main: "main",
            title: "Введение",
            task1: "Урок 1: Введение в курс ",
            task2: "Урок 2: Бизнес онлайн и офлайн",
            task3: " Урок 3: Имидж компании",
            text: " Результат модуля: вы узнаете, как будет проходить обучение, познакомитесь с трекером и другими участниками курса.",

            btn2KG: "1 жума",
            titleKG: "Киришүү ",
            task1KG: "1-сабак: курhttps://github.com/abytaeva11/school-library/pull/25/conflict?name=src%252FApp.js&ancestor_oid=52d6f51a0639c82365a8860d83c1267a2c1b6b7b&base_oid=502bb0ba842ba6bf068ca9f0db5961d41f706bdb&head_oid=3e207738e84ab871e859a0e17ce2f504b1e7607bска киришүү ",
            task2KG: "2-сабак: онлайн жана оффлайн Бизнес",
            task3KG: " 3-сабак: компаниянын имиджи",
            textKG: " Модулдун натыйжасы: тренинг кандай өтөөрүн, трекер жана курстун башка катышуучулары менен таанышууну үйрөнөсүз.",

        },
        {
            btn1: "Модуль 5",
            btn2: " 1 неделя",
            main: "main",
            title: "Введение",
            task1: "Урок 1: Введение в курс ",
            task2: "Урок 2: Бизнес онлайн и офлайн",
            task3: " Урок 3: Имидж компании",
            text: " Результат модуля: вы узнаете, как будет проходить обучение, познакомитесь с трекером и другими участниками курса.",

            btn2KG: "1 жума",
            titleKG: "Киришүү ",
            task1KG: "1-сабак: курска киришүү ",
            task2KG: "2-сабак: онлайн жана оффлайн Бизнес",
            task3KG: " 3-сабак: компаниянын имиджи",
            textKG: " Модулдун натыйжасы: тренинг кандай өтөөрүн, трекер жана курстун башка катышуучулары менен таанышууну үйрөнөсүз.",

        }
    ];
    const fakeBackend = [
        {
            id: 1,
            title: "Все разделы",
            titleKg: "Бардык бөлүмдөр",
            isDone: false,
            books: [
                {
                    id: 1,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 2,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",

                },
                {
                    id: 3,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",
                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Книги",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 4,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",
                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 5,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    img: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 6,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",
                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 7,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 8,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 9,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 7,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 8,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 9,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },

            ],

        },
        {
            id: 2,
            title: "Новое",
            titleKg: "Жаны",
            isDone: false,
            books: [
                {
                    id: 1,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 2,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 3,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 4,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 5,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 6,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 7,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 8,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 7,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 8,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 9,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 9,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },

            ],
        },
        {
            id: 3,
            title: "Софт-скилс",
            titleKg: "Софт-скилдер",
            isDone: false,
            books: [
                {
                    id: 1,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 2,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 3,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 4,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 5,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 6,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 7,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 8,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 9,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },

            ],
        },
        {
            id: 4,
            title: "Книги",
            titleKg: "китептер",
            isDone: false,
            books: [
                {
                    id: 1,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 2,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 3,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 4,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 5,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 6,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 7,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 8,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 7,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 8,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 9,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",
                },
                {
                    id: 9,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },


            ],
        },
        {
            id: 5,
            title: "Окружение",
            titleKg: "Курчоо",
            isDone: false,
            books: [
                {
                    id: 1,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",
                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 2,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 3,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 4,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 5,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 6,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 7,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 8,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 9,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 7,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 8,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: wizards,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },
                {
                    id: 9,
                    title: "С какой книги начать?",
                    text: "Полезные статьи",
                    textAll: "все",
                    textNew: "Новое",
                    textBooks: "Книги",
                    images: life,
                    author: "Автор: Muslim Bolot",
                    data: "Дата: 22.08.22",

                    titleKg: "Кайсы китептен баштоо керек?",
                    textKg: "Пайдалуу макалалар",
                    textAllKg: "Баары",
                    textNewKg: "Жаны",
                    textBooksKg: "Китептер",
                    authorKg: "Автор: Абытаева Савия",
                },

            ],
        }


    ];
    const back = [
        {
            text:{
                wifi:"Быстрые ссылки",
                bos:"Главная",
                bos1:"Школа",
                bos2:"О нас",
                wifi2:"Социальные сети",
                calling:"Контакты",
                adress:"Адрес",
                street:"ИП Сейсембай, г.Алматы, мкр. Нурлытау, ул. Мерген, 93.",
                code:"Идентификационный код: 661102300013",

                wifiKG:"Ыкчам шилтемелер",
                bosKG:"Башкы бет",
                bos1KG:"Мектеп",
                bos2KG:"Биз жөнүндө",
                wifi2KG:"Социалдык тармактар",
                callingKG:"Байланышуу",
                adressKG:"Дареги",
                streetKG:"Жеке ишкер Сейсембай, Алматы, Нурлытау кичи району, Мерген көч., 93.",
                codeKG:"Идентификациялык код: 661102300013",
            }
        }

    ];
    const head = [
        {
            text:{
                along:"Само развитие лучше чем школьное обучение",
                along2:"Здесь вы найдете все для само-обучения.",
                along3:"Подобрать пакет",
                alongKG:"Озун озу онуктуруу кыйла жакшы",
                along2KG:"Бул жерде сиз өз алдынча окуу үчүн баарын таба аласыз.",
                along3KG:"Пакет алыңыз",
            }

        }
    ];
    const pack = [
        {
            pack:{
                text:"Наши курсы",
                text1:"Получайте новые знания, навыки и возможности для эффективной жизни.",
                text3:"Подобрать пакет",
                text4:"Войти",

                textKG:"Биздин курстар",
                text1KG:"Жаңы билимдерди, көндүмдөрдү жана эффективдүү жашоо үчүн мүмкүнчүлүктөрдү алыңыз.",
                text3KG:"Пакетти алып кетүү",
                text4KG:"Кирүү",




            }
        }
    ]
    const nail = [
        {
            hero:{
                bos:"Главная",
                bos1:"Школа",
                bos2:"О нас",
                bos3:"Войти",

                bosKG:"Башкы бет",
                bos1KG:"Мектеп",
                bos2KG:"Биз жөнүндө",
                bos3KG:"Кирүү үчүн",

            }

        }
    ];

    const hero = [
        {
        you:{
            text:"Наши курсы /Курсы по созданию команды ",
            text1:"Создание команды",
            text2:"Как правильно строить команду и эффективно ею управлять, чтобы достигать все поставленные цели.",
            text3:"Получить доступ за 500,00 $ ",
            text4:"В курс входит",
            text5:"43 материала",
            text6:"100% эксклюзив",

            textKG:"Биздин курстар / Команда куруу курстары ",
            text1KG:"Команда түзүү",
            text2KG:"Бардык максаттарга жетүү үчүн команданы кантип түзүү жана аны натыйжалуу башкаруу.",
            text3KG:"00,00 долларга кирүү мүмкүнчүлүгүн алыңыз ",
            text4KG:"Курс камтыйт",
            text5KG:"43 материал",
            text6KG:"00% өзгөчө",





        }
    }
    ];
    const place = [
        {
            text:{
                title1:"О КУРСЕ",
                title2:"Как правильно строить команду и эффективно ею управлять, чтобы достигать все поставленные цели.",
                title3:"И если вы хотите достичь успеха в карьере, бизнесе, своих проектах, значит, время переходить от прокачивания личной эффективности к изучению организации и работы эффективной команды.",
                title4:"Курс “Командообразование” поможет вам освоить и внедрить методы создания и работы таких команд, которые приносят результат, потому что достижение успеха - это командный вид спорта.",
                title5:"И в работе, и в жизни выдающихся результатов достигает только тот, кто умеет окружать себя выдающимися людьми. Ваши достижения будут настолько же выдающимися, насколько выдающейся будет ваша команда. А команда будет настолько же выдающейся, насколько выдающимся будет её лидер.",
                title6:"Команда - это самая эффективная форма организации коллективного труда. Не бывает команды без эффективности. Если то, что вы называете командой, неэффективна, то скорее всего, это не команда, а группа людей, которым чего-то не хватает для того, чтобы стать командой. Сама природа создания и функционирования команды, подразумевает ее эффективность.",

                title1KG:"КУРС ЖӨНҮНДӨ",
                title2KG:"Кантип туура команда түзүү жана бардык максаттарга жетүү үчүн аны натыйжалуу башкаруу.",
                title3KG:"Ал эми карьераңызда, бизнесиңизде, долбоорлоруңузда ийгиликке жетүүнү кааласаңыз, анда жеке эффективдүүлүктү жогорулатуудан натыйжалуу команданын уюштуруу жана ишин изилдөөгө өтүүгө убакыт келди.",
                title4KG:"Команда куруу курсу натыйжаларды алып келүүчү командаларды түзүү жана иштөө ыкмаларын өздөштүрүү жана ишке ашырууга жардам берет, анткени ийгиликке жетүү бул командалык спорт.",
                title5KG:"Жумушта да, жашоодо да көрүнүктүү натыйжаларга өзүн көрүнүктүү адамдар менен курчаганды билгендер гана жетишет. Сиздин жетишкендиктериңиз, сиздин командаңыз көрүнүктүү болот. Ал эми анын лидери кандай көрүнүктүү болсо, команда да ошондой болот.",
                title6KG:"Коллектив коллективдуу эмгекти уюштуруунун эц натыйжалуу формасы болуп саналат. Натыйжалуулугу жок коллектив жок. Эгер сиз команда деп атаган нерсе эффективдүү болбосо, анда бул команда эмес, команда болуу үчүн бир нерсе жетишпеген адамдардын тобу. Коллективдин тузулушунун жана иштешинин мунезу анын натыйжалуулугун билдирет.\n",
            },
            text2:{
                title1:"Этот курс будет особо актуален для тех, кто хочет:",
                title2:"освоить навык создания эффективных команд",
                title3:"освоить принципы построения эффективных взаимоотношений в любой команде или группе.",
                title4:"сделать работу с командой плодотворной и легкой",
                title5:"значительно повысить эффективность своего бизнеса/проекта/отдела и улучшить взаимоотношения в коллективе",
                title6:"освоить специальные способы и приемы чтобы проявить свои лидерские качества",
                title7:"получать стабильный качественный результат от работы с командой",
                title8:"получать стабильный качественный результат от работы с командой",
                title9:"оценить состояние дел в своем потенциальном или уже существующем бизнесе или проекте более конструктивно и прагматично",
                title10:"значительно сократить количество ошибок в работе с командой.",

                title1KG:"Бул курс, өзгөчө, каалагандар үчүн актуалдуу болот:",
                title2KG:"натыйжалуу командаларды курууну үйрөн",
                title3KG:"кандайдыр бир коллективде же группада эффективдуу мамилелерди тузуунун принциптерин ездештуруу.",
                title4KG:"команда менен иштөө жемиштүү жана жеңил болсун",
                title5KG:"Сиздин бизнесиңиздин/долбооруңуздун/бөлүмүңүздүн натыйжалуулугун олуттуу жогорулатуу жана командадагы мамилелерди жакшыртуу",
                title6KG:"алардын лидерлик сапаттарын көрсөтүүнүн атайын ыкмаларын жана ыкмаларын үйрөнүшөт",
                title7KG:"команда менен иштөөдөн туруктуу жогорку сапаттагы натыйжаны алуу",
                title8KG:"команда менен иштөөдөн туруктуу жогорку сапаттагы натыйжаны алуу",
                title9KG:"Сиздин потенциалыңыздагы же иштеп жаткан бизнесиңиздеги же долбоордогу абалды конструктивдүү жана прагматикалык түрдө баалаңыз",
                title10KG:"коллектив менен иштееде каталардын санын бир кыйла кыскартуу.",
            },
            text3:{
                title1:"В этом курсе мы рассмотрим:",
                title2:"Что такое команда, какие бывают виды команд, для чего и как они создаются, что объединяет людей и держит в команде.",
                title3:"Лидерство - это врожденное качество или его можно приобрести?",
                title4:"Какие есть методы повышения эффективности команды.",
                title5:"Почему именно работа в команде в разы увеличивает результат.",
                title6:"Как подбирать правильных людей в команду",
                title7:"Как их обучать и продвигать по карьерной лестнице.",
                title8:"Почему люди порой не хотят меняться и причины невыполнения подчиненными ваших поручений.",
                title9:"Как правильно и своевременно увольнять подчиненных ",

                title1KG:"Бул курста биз төмөнкүлөрдү камтыйт:",
                title2KG:"Команда деген эмне, командалардын кандай түрлөрү бар, алар эмне үчүн жана кантип түзүлөт, адамдарды эмне бириктирип, командада кармап турат.\n",
                title3KG:"Лидерлик тубаса сапатпы же ага ээ болууга болобу?",
                title4KG:"Коллективдин натыйжалуулугун жогорулатуунун кандай ыкмалары бар.",
                title5KG:"Эмне үчүн командалык иш кээде натыйжаны жогорулатат.",
                title6KG:"Командага туура адамдарды кантип тандоо керек",
                title7KG:"Аларды кантип окутуп, карьералык тепкичти көтөрүү керек.",
                title8KG:"Эмне үчүн адамдар кээде өзгөргүсү келбейт жана кол алдындагылар сиздин көрсөтмөңүздү аткарбай жаткан себептер.",
                title9KG:"Кол алдындагыларды кантип туура жана өз убагында бошотуу керек",
            },
            text4:{
                title1:"Регистрируйтесь на курс, стройте эффективные команды и пусть удача сопутствует вам на этом пути!",
                title2:"* - материалы включают уроки и задания. И в конце чтобы получить сертификат вам потребуется список заданий которые вы выполнили и тест с коуч-тренером который вы пройдете в зуме для получения сертификата. Получить к ним доступ можно только при обучении с коуч-тренером.",

                title1KG:"Курска катталыңыз, эффективдүү командаларды түзүңүз жана ийгилик сизди жолдо коштоп жүрсүн!",
                title2KG:"* - материалдар сабактарды жана тапшырмаларды камтыйт. Ал эми аягында, сертификат алуу үчүн, сиз аткарган тапшырмалардын тизмеси жана сертификат алуу үчүн масштабда өтө турган машыктыруучу менен тест керек болот. Сиз аларга машыктыруучу менен машыгууда гана кире аласыз.\n",
            },
        }
    ];
    const [language, setLanguage] = useState(false)
    const getKG = () => {
        setLanguage(true)
    }
    const getRU = () => {
        setLanguage(false)
    }
    return (
        // eslint-disable-next-line react/jsx-no-undef
        <LanguageContext.Provider value={{
            language,
            data,
            head,
            back,
            place,
            nail,
            hero,
            getKG,
            getRU,
            subscribe,
            pack,
            fakeBackend,
            accordion,
            reviews,
            check

        }}>
            {children}
        </LanguageContext.Provider>
    );
};

export default RootContext;