import {LanguageContext} from "./index"
import {useState} from "react";
import wizards from "../../Pages/Tabs/img/image 1.png";
import life from "../../Pages/Tabs/img/image 2.png";
import line from "../../Pages/Rewiew/img/Line 8.png";


const RootContext = ({children}) => {
    const data = [
        {
            card: {
                title: "Подпишитесь сейчас за 250,00 $ / год",
                desc: "И получи доступ ко всем нашим материалам и начинай развиваться сейчас вместе со всеми",
                sub: "Подписаться",
                know: "Узнать больше",
                titleKG: "Абоненттүү болу үчүн 250,00 $ / жыл",
                descKG: "Жана бардык материалдарыбызга доступ алып, жана бардык баштоочулармен кызыктаныңыз",
                subKG: "Абоненттүү болуу",
                knowKG: "Кошулууну аныктап көрүү",
            },
            accord: {
                name: "Появились вопросы?",
                question1: "Сколько всего насчитывается материала всего?",
                question2: "Потеряю ли я оставшесея время если перейду на другой до окончания этого?",
                question3: "Могу ли я отказаться от автопродления подписки?",
                question4: "Откуда мне узнавать про новые статьи и курсы?",
                title: "К сожелению мы уже утратили счет материала спустьа столько лет работы и уже их настолько много что их уже не",
                nameKG: "Суроолор барбы?",
                question1KG: "Жалпыда жеткиликтүү материалдар канча?",
                question2KG: "Бул бүтөн болгондон мурун калган убактылууга четкилештиргем?",
                question3KG: "Абоненттикти авто-жаңылоо жөнүндө токтотуу болуу мүмкүнмү?",
                question4KG: "Жаңы макалалар жана курстар тууралуу кайсыл жактан кабар ала алам?",
                titleKG: "Кечиресиз, биз жумуш жылдарынан кийин материалдардын санын өзүмүз чыгарып кеттик, жана алар азайы көп болду, алар..."
            },

        }
    ];

    const reviews = [
        {
            title: "Твой опыт бесценен! Ты бьешь в самое сердце и в этом твой успех, любого бизнесмена! У меня есть шанс научиться на твоих ошибках. Этот опыт бесценен!",
            text: "Смотреть полностью",
            name: "Muslim Bolot",
            lastTitle: "Предпрениматель",
            img: line,

            titleKG:"Сиздин тажрыйба баа жеткис! Сен жүрөгүңдү согуп жатасың жана бул сенин ийгилигиң, каалаган бизнесмен! Мен сенин каталарыңдан сабак алууга мүмкүнчүлүгүм бар. Бул тажрыйба баа жеткис! ",
            textKG: "  Баардыгын коруу",
            nameKG: "Абытаева Савия",
            lastTitleKG:"Ишкер "


        },
        {
            title: "Твой опыт бесценен! Ты бьешь в самое сердце и в этом твой успех, любого бизнесмена! У меня есть шанс научиться на твоих ошибках. Этот опыт бесценен!",
            text: "Смотреть полностью",
            name: "Muslim Bolot",
            lastTitle: "Предпрениматель",
            img: line,

            titleKG:"Сиздин тажрыйба баа жеткис! Сен жүрөгүңдү согуп жатасың жана бул сенин ийгилигиң, каалаган бизнесмен! Мен сенин каталарыңдан сабак алууга мүмкүнчүлүгүм бар. Бул тажрыйба баа жеткис! ",
            textKG: "  Баардыгын коруу",
            nameKG: "Абытаева Савия",
            lastTitleKG:"Ишкер "


        },
        {
            title: "Твой опыт бесценен! Ты бьешь в самое сердце и в этом твой успех, любого бизнесмена! У меня есть шанс научиться на твоих ошибках. Этот опыт бесценен!",
            text: "Смотреть полностью",
            name: "Muslim Bolot",
            lastTitle: "Предпрениматель",
            img: line,

            titleKG:"Сиздин тажрыйба баа жеткис! Сен жүрөгүңдү согуп жатасың жана бул сенин ийгилигиң, каалаган бизнесмен! Мен сенин каталарыңдан сабак алууга мүмкүнчүлүгүм бар. Бул тажрыйба баа жеткис! ",
            textKG: "  Баардыгын коруу",
            nameKG: "Абытаева Савия",
            lastTitleKG:"Ишкер "

        },
    ];




    const subscribe = [
        {
            decor: "Оформление подписки",
            name: {
                title: "ФИО",
                input: "Muslim Bolot Joodarovich"
            },
            email: {
                title: "Електронная почта",
                input: "Example@gmail.com"
            },
            number: {
                title: "Номер телефона",
                input: "+996 770 55 55 55 "
            },
            password: {
                title: "Промокод",
                input: "If you do have"
            },
            pay: {
                title: "Оплата",
                visa: "Visa",
                card: "Master Card"
            },
            cart: {
                title: "Номер карты",
                term: "Срок",
                time: "CVV",
            },

            average: {
                title: "Уровень пакета",
                usual: "Обычный",
                usual2: "Ежемесячно",
                usual3: "Ежегодно",
                usual4: "Все новые статьи",
                usual5: "Все мастер классы по саморозвитию",
                usual6: "Цена: 225$",
                usual7: "Выбрано",
                usualCoin: "250$"
            },
            intensive: {
                title2: "Интенсив",
                careful: "Ежемесячно",
                careful1: "Ежегодно",
                careful2: "Все новые статьи",
                careful3: "Все мастер классы по саморозвитию",
                careful4: "Курс по чтению языка тела",
                careful5: "Курс по накоплению средств с выполотой долгов",
                careful6: "Курс по быстрому карьерному росту",
                careful7: "Курс по одолеванию страха потери",
                coin: "Цена: 500$",
                coin2: "750$",
                Choose: "Выбрать",
                dollar: "500$"
            },
            btn: "Оплатить ",
            agree: "Я ознакомился и согласен с Условиями оказания услуг"
        },
]

    const accordion=[

        {
            levelKG:"Курстун программасы",
            btn1:"Модуль 1",
            btn2:" 1 неделя",
            main:"main",
            title:"Введение",
            task1:"Урок 1: Введение в курс ",
            task2:"Урок 2: Бизнес онлайн и офлайн",
            task3:" Урок 3: Имидж компании",
            text:" Результат модуля: вы узнаете, как будет проходить обучение, познакомитесь с трекером и другими участниками курса.",

            btn2KG:"1 жума",
            titleKG:"Киришүү ",
            task1KG:"1-сабак: курска киришүү ",
            task2KG:"2-сабак: онлайн жана оффлайн Бизнес",
            task3KG:" 3-сабак: компаниянын имиджи",
            textKG:" Модулдун натыйжасы: тренинг кандай өтөөрүн, трекер жана курстун башка катышуучулары менен таанышууну үйрөнөсүз.",

        },
        {
            btn1:"Модуль 2",
            btn2:" 1 неделя",
            main:"main",
            title:"Введение",
            task1:"Урок 1: Введение в курс ",
            task2:"Урок 2: Бизнес онлайн и офлайн",
            task3:" Урок 3: Имидж компании",
            text:" Результат модуля: вы узнаете, как будет проходить обучение, познакомитесь с трекером и другими участниками курса.",

            btn2KG:"1 жума",
            titleKG:"Киришүү ",
            task1KG:"1-сабак: курска киришүү ",
            task2KG:"2-сабак: онлайн жана оффлайн Бизнес",
            task3KG:" 3-сабак: компаниянын имиджи",
            textKG:" Модулдун натыйжасы: тренинг кандай өтөөрүн, трекер жана курстун башка катышуучулары менен таанышууну үйрөнөсүз.",

        },
        {
            btn1:"Модуль 3",
            btn2:" 1 неделя",
            main:"main",
            title:"Введение",
            task1:"Урок 1: Введение в курс ",
            task2:"Урок 2: Бизнес онлайн и офлайн",
            task3:" Урок 3: Имидж компании",
            text:" Результат модуля: вы узнаете, как будет проходить обучение, познакомитесь с трекером и другими участниками курса.",

            btn2KG:"1 жума",
            titleKG:"Киришүү ",
            task1KG:"1-сабак: курска киришүү ",
            task2KG:"2-сабак: онлайн жана оффлайн Бизнес",
            task3KG:" 3-сабак: компаниянын имиджи",
            textKG:" Модулдун натыйжасы: тренинг кандай өтөөрүн, трекер жана курстун башка катышуучулары менен таанышууну үйрөнөсүз.",

        },
        {
            btn1:"Модуль 4",
            btn2:" 1 неделя",
            main:"main",
            title:"Введение",
            task1:"Урок 1: Введение в курс ",
            task2:"Урок 2: Бизнес онлайн и офлайн",
            task3:" Урок 3: Имидж компании",
            text:" Результат модуля: вы узнаете, как будет проходить обучение, познакомитесь с трекером и другими участниками курса.",

            btn2KG:"1 жума",
            titleKG:"Киришүү ",
            task1KG:"1-сабак: курска киришүү ",
            task2KG:"2-сабак: онлайн жана оффлайн Бизнес",
            task3KG:" 3-сабак: компаниянын имиджи",
            textKG:" Модулдун натыйжасы: тренинг кандай өтөөрүн, трекер жана курстун башка катышуучулары менен таанышууну үйрөнөсүз.",

        },
        {
            btn1:"Модуль 5",
            btn2:" 1 неделя",
            main:"main",
            title:"Введение",
            task1:"Урок 1: Введение в курс ",
            task2:"Урок 2: Бизнес онлайн и офлайн",
            task3:" Урок 3: Имидж компании",
            text:" Результат модуля: вы узнаете, как будет проходить обучение, познакомитесь с трекером и другими участниками курса.",

            btn2KG:"1 жума",
            titleKG:"Киришүү ",
            task1KG:"1-сабак: курска киришүү ",
            task2KG:"2-сабак: онлайн жана оффлайн Бизнес",
            task3KG:" 3-сабак: компаниянын имиджи",
            textKG:" Модулдун натыйжасы: тренинг кандай өтөөрүн, трекер жана курстун башка катышуучулары менен таанышууну үйрөнөсүз.",

        }
    ]

    const fakeBackend=[
        {
            id:1,
            title:"Все разделы",
            titleKg :"Бардык бөлүмдөр",
            isDone:false,
            books:[
                {
                    id:1,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:2,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",

                },
                {
                    id:3,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",
                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:4,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",
                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:5,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    img:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:6,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",
                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:7,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:8,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:9,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:7,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:8,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:9,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },

            ],

        },
        {
            id:2,
            title:"Новое",
            titleKg:"Жаны",
            isDone:false,
            books:[
                {
                    id:1,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:2,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:3,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:4,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:5,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:6,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:7,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:8,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:7,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:8,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:9,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:9,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },

            ],
        },
        {
            id:3,
            title:"Софт-скилс",
            titleKg:"Софт-скилдер",
            isDone:false,
            books:[
                {
                    id:1,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:2,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:3,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:4,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:5,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:6,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:7,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:8,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:9,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },

            ],
        },
        {
            id:4,
            title:"Книги",
            titleKg:"китептер",
            isDone:false,
            books:[
                {
                    id:1,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:2,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:3,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:4,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:5,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:6,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:7,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:8,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:7,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:8,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:9,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",
                },
                {
                    id:9,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },



            ],
        },
        {
            id:5,
            title:"Окружение",
            titleKg: "Курчоо",
            isDone:false,
            books:[
                {
                    id:1,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",
                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:2,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Китептер",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:3,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Китептер",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:4,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:5,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:6,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:7,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:8,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:9,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:7,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:8,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:wizards,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },
                {
                    id:9,
                    title:"С какой книги начать?",
                    text:"Полезные статьи",
                    textAll:"все",
                    textNew:"Новое",
                    textBooks:"Книги",
                    images:life,
                    author:"Автор: Muslim Bolot",
                    data:"Дата: 22.08.22",

                    titleKg:"Кайсы китептен баштоо керек?",
                    textKg:"Пайдалуу макалалар",
                    textAllKg:"Баары",
                    textNewKg:"Жаны",
                    textBooksKg:"Книги",
                    authorKg:"Автор: Абытаева Савия",
                },

            ],
        }


    ]

    const back = [
        {

        }

    ]
    const [language, setLanguage] = useState(false)
    const getKG = () => {
        setLanguage(true)
    }
    const getRU = () => {
        setLanguage(false)
    }
    return (
        // eslint-disable-next-line react/jsx-no-undef
        <LanguageContext.Provider value={{
            language,
            data,
            getKG,
            getRU,
            subscribe,
            fakeBackend,
            accordion,
            reviews,

        }}>
            {children}
        </LanguageContext.Provider>
    );
};

export default RootContext;